### DISCUSSION TITLE
app.toml specifications

### DISCUSSION THREAD

**Discussion by aadee92** [oxidecomputer/hubris#1414] [Q&A] [answered]
Is there any documentation on what each entry in the app.toml file means?

Specifically, what do these entries define?:
``` toml
task-slots = ["..."]
uses = ["...", "..."]
```
