### ISSUE TITLE
Allow for multiple names in memory definitions

### ISSUE THREAD

**Issue by mkeeter** [oxidecomputer/hubris#1247]
It would be nice if we could specify `names = ["a", "b", "stage0"]` instead of repeating 3x:
```toml
[[sram3]]
name = "a"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false

[[sram3]]
name = "b"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false

[[sram3]]
name = "stage0"
address = 0x40102000
size = 0x1000
read = true
write = false
execute = false
```
(from [here](https://github.com/oxidecomputer/hubris/blob/master/chips/lpc55/memory.toml#L56))
