### ISSUE TITLE
Wouldn't it be nice to refer to interrupts in the TOML by name

### ISSUE THREAD

**Issue by cbiffle** [oxidecomputer/hubris#185]
Currently we're doing stuff like

```toml
[tasks.spi_driver]
# irrelevant bits omitted
interrupts = {51 = 1}
```

Good old interrupt 51. ...

Better would be

```toml
interrupts = {spi3 = 1}
```

The SVD files consumed by the PAC crates during their build process contain enough information to do this, but the PAC crates don't produce any kind of reflective interface we could use to reason about interrupts on x86. Too bad, that. We may have to build our own thing.
