### ISSUE TITLE
`xtask flash` should get its instructions from app.toml somehow

### ISSUE THREAD

**Issue by cbiffle** [oxidecomputer/hubris#255]
`xtask flash` currently has a hardcoded table of board names for finding flashing config files. That's going to become annoying. It should take direction from app.toml instead.

I'm imagining something like

```toml
[flashing]
method = "openocd"
config = "../whatever.cfg"
```
where the paths are relative to the app.toml itself, as usual.
