### ISSUE TITLE
Reduce duplication in task slot descriptions

### ISSUE THREAD

**Issue by mkeeter** [oxidecomputer/hubris#314]
The most common use of `task-slots` in `app.toml` adds a bunch of repetition, because it maps slot names to (identical) task names.

We should switch `task-slots` to an array and assume that strings within the array are `{ a = "a" }` identity mappings.

```toml
[tasks.vsc7448]
path = "../../task/vsc7448"
name = "task-vsc7448"
priority = 3
requires = {flash = 65536, ram = 8192}
stacksize = 2048
start = true
task-slots = [
    { peer = "pong" },
    "usart_driver"
]
```
